[package]
name = "compl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstest = "0.19.0"
itertools = "0.12.1"
rand = "0.9.0-alpha.1"
lazy_static = "1.4.0"